In [ ]:
import numpy as np

In [ ]:
l=[1,2,3,4]
arr=np.array(l)

In [ ]:
id(arr)

140318271169520

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.shape

(4,)

In [ ]:
l=[[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
arr=np.array(l)

In [ ]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr.shape

(3, 3)

In [ ]:
identity_matrix=np.identity(3)

In [ ]:
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [ ]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [ ]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
np.arrange(0,10,10)

AttributeError: ignored

In [ ]:
np.random.rand(4)

array([0.8409091 , 0.46561586, 0.93255398, 0.47554856])

In [ ]:
np.random.rand(4,5,3)

array([[[0.18315285, 0.75333366, 0.03228297],
        [0.37474995, 0.64086197, 0.77777551],
        [0.21444182, 0.09292192, 0.53662887],
        [0.29707507, 0.27089097, 0.80720113],
        [0.38116672, 0.60266298, 0.21897046]],

       [[0.42154653, 0.5230385 , 0.14613088],
        [0.50123374, 0.92814044, 0.25090989],
        [0.69537415, 0.28520876, 0.85674153],
        [0.9931111 , 0.02763813, 0.94265858],
        [0.34456959, 0.46447323, 0.65270781]],

       [[0.32516719, 0.90464569, 0.19361348],
        [0.8459584 , 0.64962554, 0.69197629],
        [0.21774883, 0.1627859 , 0.36775386],
        [0.18750796, 0.47307376, 0.24403308],
        [0.29721908, 0.86212927, 0.75797801]],

       [[0.06128789, 0.22629911, 0.39402841],
        [0.80435253, 0.86299454, 0.39418276],
        [0.4860797 , 0.6526772 , 0.21544824],
        [0.26362019, 0.11309616, 0.95153521],
        [0.97539106, 0.30302458, 0.54779207]]])

In [ ]:
np.random.randint(10,50)

33

In [ ]:
np.random.randint(10,50,10)

array([36, 12, 36, 17, 36, 19, 33, 12, 26, 26])

In [ ]:
import random
random.seed(15)

In [ ]:
random.randint(5,10)

6

In [ ]:
arr=np.array([1,2,3,4])

In [ ]:
print(arr)

[1 2 3 4]


In [ ]:
arr[0]

1

In [ ]:
arr[-1]

4

In [ ]:
arr[1:]

array([2, 3, 4])

In [ ]:
## Indexing 2D array

array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
array_2d[1,1]

5

In [ ]:
array_2d[1]

array([4, 5, 6])

In [ ]:
array_2d[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_2d[:2,0:2]

array([[1, 2],
       [4, 5]])

In [ ]:
array_2d[0:3,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array_2d[2,:]

array([7, 8, 9])

In [ ]:
array_2d[:,2]

array([3, 6, 9])

In [ ]:
l=[[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
l[:][2]

[7, 8, 9]

In [ ]:
array_2d[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
array_2d[:,0]

array([1, 4, 7])

In [ ]:
array_2d[0,:]

array([1, 2, 3])

In [ ]:
## Indexing 2D array

array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
array_2d[array_2d>6]

array([7, 8, 9])

In [ ]:
array_2d[array_2d%2==0]

array([2, 4, 6, 8])

In [ ]:
array_2d[array_2d%2!=0]

array([1, 3, 5, 7, 9])

In [ ]:
array_2d[(array_2d%2!=0) & (array_2d>5)]

array([7, 9])

In [ ]:
array_2d>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [ ]:
arr1=np.arange(0,5)
arr2=np.arange(6,11)

In [ ]:
print(arr1)

[0 1 2 3 4]


In [ ]:
print(arr2)

[ 6  7  8  9 10]


In [ ]:
arr1+arr2

array([ 6,  8, 10, 12, 14])

In [ ]:
arr1-arr2

array([-6, -6, -6, -6, -6])

In [ ]:
arr1*arr2

array([ 0,  7, 16, 27, 40])

In [ ]:
arr2/arr1

<ipython-input-101-e2e60495effe>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr2/arr1


array([inf, 7. , 4. , 3. , 2.5])

In [ ]:
arr1/arr2

array([0.        , 0.14285714, 0.25      , 0.33333333, 0.4       ])

In [ ]:
arr1**2

array([ 0,  1,  4,  9, 16])

In [ ]:
arr1=np.arange(0,5)
arr2=np.arange(6,11)

In [ ]:
print(arr1)

[0 1 2 3 4]


In [ ]:
print(arr2)

[ 6  7  8  9 10]


In [ ]:
np.add(arr1,arr2)

array([ 6,  8, 10, 12, 14])

In [ ]:
np.subtract(arr2,arr1)

array([6, 6, 6, 6, 6])

In [ ]:
np.multiply(arr1,arr2)

array([ 0,  7, 16, 27, 40])

In [ ]:
np.divide(arr2,arr1)

<ipython-input-21-6a0bd0e0205e>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(arr2,arr1)


array([inf, 7. , 4. , 3. , 2.5])

In [ ]:
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.sin(arr2)

array([-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [ ]:
np.cos(arr1)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
np.tan(arr1)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [ ]:
np.exp(arr2)

array([  403.42879349,  1096.63315843,  2980.95798704,  8103.08392758,
       22026.46579481])

In [ ]:
np.min(arr1)

0

In [ ]:
np.min(arr2)

6

In [ ]:
np.max(arr2)

10

In [ ]:
## Indexing 2D array

array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
np.max(array_2d)

9

In [ ]:
np.average(array_2d)

5.0

In [ ]:
np.mean(array_2d)

5.0

In [ ]:
array_2d.shape

(3, 3)

In [ ]:
arr3=array_2d.reshape(9)

In [ ]:
arr3.shape

(9,)

In [ ]:
## Indexing 2D array

array_2d = np.array([[1,2,3,10],[4,5,6,12],[7,8,9,13]])

In [ ]:
array_2d.shape

(3, 4)

In [ ]:
array_2d

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 12],
       [ 7,  8,  9, 13]])

In [ ]:
arr4=array_2d.reshape(4,3)

In [ ]:
arr4.shape

(4, 3)

In [ ]:
arr4

array([[ 1,  2,  3],
       [10,  4,  5],
       [ 6, 12,  7],
       [ 8,  9, 13]])

In [ ]:
## Indexing 2D array

array_2d = np.array([[1,2,3,10],[4,5,6,12],[7,8,9,13]])
arr5=np.array([[14,15,16,17]])

In [ ]:
array_2d

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 12],
       [ 7,  8,  9, 13]])

In [ ]:
arr5

array([[14, 15, 16, 17]])

In [ ]:
arr6=np.concatenate((array_2d,arr5),axis=0)

In [ ]:
arr6

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 12],
       [ 7,  8,  9, 13],
       [14, 15, 16, 17]])

In [ ]:
np.sort(arr6)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 12],
       [ 7,  8,  9, 13],
       [14, 15, 16, 17]])

In [ ]:
arr5=np.array([18,20,16,17])

In [ ]:
arr5

array([18, 20, 16, 17])

In [ ]:
np.sort(arr5)

array([16, 17, 18, 20])